server:
  port: 8082

spring:
  security:
    user:
      name: account
      password: account
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-account-changelog.xml
    default_schema: account

  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: account
    password: account
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: account
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account.group
      concurrency: 1
      max.poll.interval.ms: 1000
      spring.json.trusted.packages: ru.skillbox.diplom.group35.*
    producer:
      retries: 3
    topic:
      account: topic.account
      partition-count: 1
      replication-factor: 1
      birthday-notification: event

springdoc:
  api-docs:
    enabled: true
    path: '/api/v1/account/v3/api-docs'
  swagger-ui:
    path: '/api/v1/account/swagger-ui'
    doc-expansion: none
    disable-swagger-default-url: true

logging:
  level:
    org.springframework: info
    org.apache.kafka: error